//Basketball Live Stat Book
//Created by: msteph22

//Imports
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BballUI extends javax.swing.JFrame {

    Player player1 = new Player();
    Player player2 = new Player();
    Player player3 = new Player();
    Player player4 = new Player();
    Player player5 = new Player();
    Player playerOpp = new Player();
    
    //Flags for button combos
    boolean flag1 = false;
    boolean flag2 = false;
    boolean flag3 = false;
    boolean flag4 = false;
    boolean flag5 = false;
    boolean flagOpp = false;

    //Team Stats
    int teamScore;
    int teamftMake;
    int teamftMiss;
    int teamftAtt;
    double teamftPerc;
    int teamtwoMake;
    int teamtwoMiss;
    int teamtwoAtt;
    double teamtwoPerc;
    int teamthreeMake;
    int teamthreeMiss;
    int teamthreeAtt;
    double teamthreePerc;
    int teamoffRebound;
    int teamdefRebound;
    int teamtotalRebound;
    int teamAssist;
    int teamTurnover;
    int teamSteal;
    int teamBlock;
    int teamFoul;
    
    /**
     * Creates new form BballUI
     */
    public BballUI() {
        initComponents();
        refreshTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        player1But = new javax.swing.JButton();
        player2But = new javax.swing.JButton();
        player3But = new javax.swing.JButton();
        player4But = new javax.swing.JButton();
        player5But = new javax.swing.JButton();
        oppBut = new javax.swing.JButton();
        RBSubtract = new javax.swing.JRadioButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        teamScoreBoard = new javax.swing.JLabel();
        oppScoreBoard = new javax.swing.JLabel();
        teamFoulBoard = new javax.swing.JLabel();
        oppFoulBoard = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ftMakeButton = new javax.swing.JButton();
        twoMakeButton = new javax.swing.JButton();
        threeMakeButton = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        ftMissButton = new javax.swing.JButton();
        twoMissButton = new javax.swing.JButton();
        threeMissButton = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        offReboundButton = new javax.swing.JButton();
        assistButton = new javax.swing.JButton();
        turnoverButton = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        defReboundButton = new javax.swing.JButton();
        stealButton = new javax.swing.JButton();
        blockButton = new javax.swing.JButton();
        foulButton = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayList = new javax.swing.JList();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        statTable = new javax.swing.JTable();
        tableRefreshButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        statTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuEditNames = new javax.swing.JMenu();
        menuNameEdit1 = new javax.swing.JMenuItem();
        menuNameEdit2 = new javax.swing.JMenuItem();
        menuNameEdit3 = new javax.swing.JMenuItem();
        menuNameEdit4 = new javax.swing.JMenuItem();
        menuNameEdit5 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        player1But.setText("Player 1");
        player1But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1ButActionPerformed(evt);
            }
        });

        player2But.setText("Player 2");
        player2But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2ButActionPerformed(evt);
            }
        });

        player3But.setText("Player 3");
        player3But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player3ButActionPerformed(evt);
            }
        });

        player4But.setText("Player 4");
        player4But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player4ButActionPerformed(evt);
            }
        });

        player5But.setText("Player 5");
        player5But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player5ButActionPerformed(evt);
            }
        });

        oppBut.setText("Opponent");
        oppBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oppButActionPerformed(evt);
            }
        });

        RBSubtract.setText("Subtract");
        RBSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBSubtractActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(player1But, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(player2But, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(player3But, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(player4But, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(player5But, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBSubtract)
                    .addComponent(oppBut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(player3But, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player2But, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player1But, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(player4But, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(player5But, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(oppBut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(RBSubtract)))
                .addGap(26, 26, 26))
        );

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Team");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Opp");

        teamScoreBoard.setBackground(new java.awt.Color(204, 204, 204));
        teamScoreBoard.setFont(new java.awt.Font("Verdana", 1, 35)); // NOI18N
        teamScoreBoard.setForeground(new java.awt.Color(255, 0, 0));
        teamScoreBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teamScoreBoard.setText("00");
        teamScoreBoard.setToolTipText("");
        teamScoreBoard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        oppScoreBoard.setFont(new java.awt.Font("Verdana", 1, 35)); // NOI18N
        oppScoreBoard.setForeground(new java.awt.Color(255, 0, 0));
        oppScoreBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oppScoreBoard.setText("00");
        oppScoreBoard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        teamFoulBoard.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        teamFoulBoard.setForeground(new java.awt.Color(255, 204, 0));
        teamFoulBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teamFoulBoard.setText("0");
        teamFoulBoard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        oppFoulBoard.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        oppFoulBoard.setForeground(new java.awt.Color(255, 204, 0));
        oppFoulBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oppFoulBoard.setText("0");
        oppFoulBoard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Fouls");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fouls");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teamFoulBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teamScoreBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(oppFoulBoard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(oppScoreBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamScoreBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oppScoreBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oppFoulBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamFoulBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(102, 102, 102));
        jPanel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jPanel4.setBackground(new java.awt.Color(0, 204, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Makes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        ftMakeButton.setText("FT");
        ftMakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftMakeButtonActionPerformed(evt);
            }
        });

        twoMakeButton.setText("2");
        twoMakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoMakeButtonActionPerformed(evt);
            }
        });

        threeMakeButton.setText("3");
        threeMakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeMakeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(twoMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(threeMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(ftMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ftMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(twoMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(threeMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(204, 0, 0));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Misses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        ftMissButton.setText("FT");
        ftMissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftMissButtonActionPerformed(evt);
            }
        });

        twoMissButton.setText("2");
        twoMissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoMissButtonActionPerformed(evt);
            }
        });

        threeMissButton.setText("3");
        threeMissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeMissButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(threeMissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(twoMissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(ftMissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ftMissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(twoMissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(threeMissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(204, 204, 204));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Offense"));

        offReboundButton.setText("Rebound");
        offReboundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offReboundButtonActionPerformed(evt);
            }
        });

        assistButton.setText("Assist");
        assistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assistButtonActionPerformed(evt);
            }
        });

        turnoverButton.setText("Turnover");
        turnoverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnoverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(offReboundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(turnoverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(offReboundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turnoverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Defense"));

        defReboundButton.setText("Rebound");
        defReboundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defReboundButtonActionPerformed(evt);
            }
        });

        stealButton.setText("Steal");
        stealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stealButtonActionPerformed(evt);
            }
        });

        blockButton.setText("Block");
        blockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(defReboundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stealButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stealButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(defReboundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        foulButton.setText("Foul");
        foulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foulButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(foulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(foulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(displayList);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("User Interface", jPanel9);

        jPanel17.setBackground(new java.awt.Color(102, 102, 102));

        statTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(statTable);

        tableRefreshButton.setText("Refresh");
        tableRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableRefreshButtonActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setText("Player Stats");

        statTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(statTable2);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Team Stats");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(235, 235, 235)
                .addComponent(tableRefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tableRefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stat Sheet", jPanel17);

        jMenu1.setText("Bball");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menuEditNames.setText("Edit Player Names");

        menuNameEdit1.setText("Player 1");
        menuNameEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNameEdit1ActionPerformed(evt);
            }
        });
        menuEditNames.add(menuNameEdit1);

        menuNameEdit2.setText("Player 2");
        menuNameEdit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNameEdit2ActionPerformed(evt);
            }
        });
        menuEditNames.add(menuNameEdit2);

        menuNameEdit3.setText("Player 3");
        menuNameEdit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNameEdit3ActionPerformed(evt);
            }
        });
        menuEditNames.add(menuNameEdit3);

        menuNameEdit4.setText("Player4");
        menuNameEdit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNameEdit4ActionPerformed(evt);
            }
        });
        menuEditNames.add(menuNameEdit4);

        menuNameEdit5.setText("Player 5");
        menuNameEdit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNameEdit5ActionPerformed(evt);
            }
        });
        menuEditNames.add(menuNameEdit5);

        jMenu2.add(menuEditNames);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultListModel mod = new DefaultListModel();
    
    
    private void menuNameEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNameEdit1ActionPerformed
        // Edit name of Player 1
        String newName = "";
            while(newName.equals("")){
                newName = JOptionPane.showInputDialog(this, "Type in new name or number for " + player1.getName() + " :");
            }
        player1.setName(newName);
        player1But.setText(player1.getName());
        menuNameEdit1.setText(newName);
    }//GEN-LAST:event_menuNameEdit1ActionPerformed

    private void menuNameEdit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNameEdit2ActionPerformed
        // Edit name of Player 2
        String newName = "";
            while(newName.equals("")){
                newName = JOptionPane.showInputDialog(this, "Type in new name or number for " + player2.getName() + " :");
            }
        player2.setName(newName);
        player2But.setText(player2.getName());
        menuNameEdit2.setText(newName);
    }//GEN-LAST:event_menuNameEdit2ActionPerformed

    private void menuNameEdit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNameEdit3ActionPerformed
        // Edit name of Player 3
        String newName = "";
            while(newName.equals("")){
                newName = JOptionPane.showInputDialog(this, "Type in new name or number for " + player3.getName() + " :");
            }
        player3.setName(newName);
        player3But.setText(player3.getName());
        menuNameEdit3.setText(newName);
    }//GEN-LAST:event_menuNameEdit3ActionPerformed

    private void menuNameEdit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNameEdit4ActionPerformed
        // Edit name of Player 4
        String newName = "";
            while(newName.equals("")){
                newName = JOptionPane.showInputDialog(this, "Type in new name or number for " + player4.getName() + " :");
            }
        player4.setName(newName);
        player4But.setText(player4.getName());
        menuNameEdit4.setText(newName);
    }//GEN-LAST:event_menuNameEdit4ActionPerformed

    private void menuNameEdit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNameEdit5ActionPerformed
        // Edit name of Player 5
        String newName = "";
            while(newName.equals("")){
                newName = JOptionPane.showInputDialog(this, "Type in new name or number for " + player5.getName() + " :");
            }
        player5.setName(newName);
        player5But.setText(player5.getName());
        menuNameEdit5.setText(newName);
    }//GEN-LAST:event_menuNameEdit5ActionPerformed

    private void tableRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableRefreshButtonActionPerformed
        refreshTable();
    }//GEN-LAST:event_tableRefreshButtonActionPerformed

    private void foulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foulButtonActionPerformed
        displayList.setModel(mod);
        // Foul Actions and Logs
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subFoul();
                mod.addElement("sub player1"  + " Foul " +  player1.getFoul());
            }else if(flag2 == true){
                player2.subFoul();
                mod.addElement("sub player2 " + " Foul " +  player2.getFoul());
            }else if(flag3 == true){
                player3.subFoul();
                mod.addElement("sub player3 " + " Foul " +  player3.getFoul());
            }else if(flag4 == true){
                player4.subFoul();
                mod.addElement("sub player4 " + " Foul " +  player4.getFoul());
            }else if(flag5 == true){
                player5.subFoul();
                mod.addElement("sub player5 " + " Foul " +  player5.getFoul());
            }else if(flagOpp == true){
                playerOpp.subFoul();
                mod.addElement("sub Opponent " + " Foul " +  playerOpp.getFoul());
            }
        }else{
            if (flag1 == true){
                player1.addFoul();
                mod.addElement("player1 " + " Foul " +  player1.getFoul());
            }else if(flag2 == true){
                player2.addFoul();
                mod.addElement("player2 " + " Foul " +  player2.getFoul());
            }else if(flag3 == true){
                player3.addFoul();
                mod.addElement("player3 " + " Foul " +  player3.getFoul());
            }else if(flag4 == true){
                player4.addFoul();
                mod.addElement("player4 " + " Foul " +  player4.getFoul());
            }else if(flag5 == true){
                player5.addFoul();
                mod.addElement("player5 " + " Foul " +  player5.getFoul());
            }else if(flagOpp == true){
                playerOpp.addFoul();
                mod.addElement("Opponent " + " Foul " +  playerOpp.getFoul());
            }
        }
        refreshScoreboard();
    }//GEN-LAST:event_foulButtonActionPerformed

    private void blockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockButtonActionPerformed
        displayList.setModel(mod);
        // Block Actions and Logs
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subBlock();
                mod.addElement("sub player1 " + " Block " +  player1.getBlock());
            }else if(flag2 == true){
                player2.subBlock();
                mod.addElement("sub player2 " + " Block " +  player2.getBlock());
            }else if(flag3 == true){
                player3.subBlock();
                mod.addElement("sub player3 " + " Block " +  player3.getBlock());
            }else if(flag4 == true){
                player4.subBlock();
                mod.addElement("sub player4 " + " Block " +  player4.getBlock());
            }else if(flag5 == true){
                player5.subBlock();
                mod.addElement("sub player5 " + " Block " +  player5.getBlock());
            }else if(flagOpp == true){
                playerOpp.subBlock();
                mod.addElement("sub Opponent " + " Block " +  playerOpp.getBlock());
            }
        }else{
            if (flag1 == true){
                player1.addBlock();
                mod.addElement("player1 " + " Block " +  player1.getBlock());
            }else if(flag2 == true){
                player2.addBlock();
                mod.addElement("player2 " + " Block " +  player2.getBlock());
            }else if(flag3 == true){
                player3.addBlock();
                mod.addElement("player3 " + " Block " +  player3.getBlock());
            }else if(flag4 == true){
                player4.addBlock();
                mod.addElement("player4 " + " Block " +  player4.getBlock());
            }else if(flag5 == true){
                player5.addBlock();
                mod.addElement("player5 " + " Block " +  player5.getBlock());
            }else if(flagOpp == true){
                playerOpp.addBlock();
                mod.addElement("Opponent " + " Block " +  playerOpp.getBlock());
            }
        }
        refreshScoreboard();
    }//GEN-LAST:event_blockButtonActionPerformed

    private void stealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stealButtonActionPerformed
        displayList.setModel(mod);
        // Steal Actions and Logs
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subSteal();
                mod.addElement("sub player1 " + " Steal " +  player1.getSteal());
            }else if(flag2 == true){
                player2.subSteal();
                mod.addElement("sub player2 " + " Steal " +  player2.getSteal());
            }else if(flag3 == true){
                player3.subSteal();
                mod.addElement("sub player3 " + " Steal " +  player3.getSteal());
            }else if(flag4 == true){
                player4.subSteal();
                mod.addElement("sub player4 " + " Steal " +  player4.getSteal());
            }else if(flag5 == true){
                player5.subSteal();
                mod.addElement("sub player5 " + " Steal " +  player5.getSteal());
            }else if(flagOpp == true){
                playerOpp.subSteal();
                mod.addElement("sub Opponent " + " Steal " +  playerOpp.getSteal());
            }
        }else{
            if (flag1 == true){
                player1.addSteal();
                mod.addElement("player1 " + " Steal " +  player1.getSteal());
            }else if(flag2 == true){
                player2.addSteal();
                mod.addElement("player2 " + " Steal " +  player2.getSteal());
            }else if(flag3 == true){
                player3.addSteal();
                mod.addElement("player3 " + " Steal " +  player3.getSteal());
            }else if(flag4 == true){
                player4.addSteal();
                mod.addElement("player4 " + " Steal " +  player4.getSteal());
            }else if(flag5 == true){
                player5.addSteal();
                mod.addElement("player5 " + " Steal " +  player5.getSteal());
            }else if(flagOpp == true){
                playerOpp.addSteal();
                mod.addElement("Opponent " + " Steal " +  playerOpp.getSteal());
            }
        }
        refreshScoreboard();
    }//GEN-LAST:event_stealButtonActionPerformed

    private void defReboundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defReboundButtonActionPerformed
        displayList.setModel(mod);
        // Defensive Rebound Actions and Logs
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subdefRebound();
                mod.addElement("sub player1 " + " Def Rebound " +  player1.getdefRebound());
            }else if(flag2 == true){
                player2.subdefRebound();
                mod.addElement("sub player2 " + " Def Rebound " +  player2.getdefRebound());
            }else if(flag3 == true){
                player3.subdefRebound();
                mod.addElement("sub player3 " + " Def Rebound " +  player3.getdefRebound());
            }else if(flag4 == true){
                player4.subdefRebound();
                mod.addElement("sub player4 " + " Def Rebound " +  player4.getdefRebound());
            }else if(flag5 == true){
                player5.subdefRebound();
                mod.addElement("sub player5 " + " Def Rebound " +  player5.getdefRebound());
            }else if(flagOpp == true){
                playerOpp.subdefRebound();
                mod.addElement("sub Opponent " + " Def Rebound " +  playerOpp.getdefRebound());
            }
        }else{
            if (flag1 == true){
                player1.adddefRebound();
                mod.addElement("player1 " + " Def Rebound " +  player1.getdefRebound());
            }else if(flag2 == true){
                player2.adddefRebound();
                mod.addElement("player2 " + " Def Rebound " +  player2.getdefRebound());
            }else if(flag3 == true){
                player3.adddefRebound();
                mod.addElement("player3 " + " Def Rebound " +  player3.getdefRebound());
            }else if(flag4 == true){
                player4.adddefRebound();
                mod.addElement("player4 " + " Def Rebound " +  player4.getdefRebound());
            }else if(flag5 == true){
                player5.adddefRebound();
                mod.addElement("player5 " + " Def Rebound " +  player5.getdefRebound());
            }else if(flagOpp == true){
                playerOpp.adddefRebound();
                mod.addElement("Opponent " + " Def Rebound " +  playerOpp.getdefRebound());
            }
        }
        refreshScoreboard();
    }//GEN-LAST:event_defReboundButtonActionPerformed

    private void turnoverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnoverButtonActionPerformed
        displayList.setModel(mod);
        // Turnover Actions and Logs
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subTurnover();
                mod.addElement("sub player1 " + " Turnover " +  player1.getTurnover());
            }else if(flag2 == true){
                player2.subTurnover();
                mod.addElement("sub player2 " + " Turnover " +  player2.getTurnover());
            }else if(flag3 == true){
                player3.subTurnover();
                mod.addElement("sub player3 " + " Turnover " +  player3.getTurnover());
            }else if(flag4 == true){
                player4.subTurnover();
                mod.addElement("sub player4 " + " Turnover " +  player4.getTurnover());
            }else if(flag5 == true){
                player5.subTurnover();
                mod.addElement("sub player5 " + " Turnover " +  player5.getTurnover());
            }else if(flagOpp == true){
                playerOpp.subTurnover();
                mod.addElement("sub Opponent " + " Turnover " +  playerOpp.getTurnover());
            }
        }else{
            if (flag1 == true){
                player1.addTurnover();
                mod.addElement("player1 " + " Turnover " +  player1.getTurnover());
            }else if(flag2 == true){
                player2.addTurnover();
                mod.addElement("player2 " + " Turnover " +  player2.getTurnover());
            }else if(flag3 == true){
                player3.addTurnover();
                mod.addElement("player3 " + " Turnover " +  player3.getTurnover());
            }else if(flag4 == true){
                player4.addTurnover();
                mod.addElement("player4 " + " Turnover " +  player4.getTurnover());
            }else if(flag5 == true){
                player5.addTurnover();
                mod.addElement("player5 " + " Turnover " +  player5.getTurnover());
            }else if(flagOpp == true){
                playerOpp.addTurnover();
                mod.addElement("Opponent " + " Turnover " +  playerOpp.getTurnover());
            }
        }
        refreshScoreboard();
    }//GEN-LAST:event_turnoverButtonActionPerformed

    private void assistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assistButtonActionPerformed
        displayList.setModel(mod);
        // Assists Actions and Logs
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subAssist();
                mod.addElement("sub player1 " + " Assist " +  player1.getAssist());
            }else if(flag2 == true){
                player2.subAssist();
                mod.addElement("sub player2 " + " Assist " +  player2.getAssist());
            }else if(flag3 == true){
                player3.subAssist();
                mod.addElement("sub player3 " + " Assist " +  player3.getAssist());
            }else if(flag4 == true){
                player4.subAssist();
                mod.addElement("sub player4 " + " Assist " +  player4.getAssist());
            }else if(flag5 == true){
                player5.subAssist();
                mod.addElement("sub player5 " + " Assist " +  player5.getAssist());
            }else if(flagOpp == true){
                playerOpp.subAssist();
                mod.addElement("sub Opponent " + " Assist " +  playerOpp.getAssist());
            }
        }else{
            if (flag1 == true){
                player1.addAssist();
                mod.addElement("player1 " + " Assist " +  player1.getAssist());
            }else if(flag2 == true){
                player2.addAssist();
                mod.addElement("player2 " + " Assist " +  player2.getAssist());
            }else if(flag3 == true){
                player3.addAssist();
                mod.addElement("player3 " + " Assist " +  player3.getAssist());
            }else if(flag4 == true){
                player4.addAssist();
                mod.addElement("player4 " + " Assist " +  player4.getAssist());
            }else if(flag5 == true){
                player5.addAssist();
                mod.addElement("player5 " + " Assist " +  player5.getAssist());
            }else if(flagOpp == true){
                playerOpp.addAssist();
                mod.addElement("Opponent " + " Assist " +  playerOpp.getAssist());
            }
        }
        refreshScoreboard();
    }//GEN-LAST:event_assistButtonActionPerformed

    private void offReboundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offReboundButtonActionPerformed
        displayList.setModel(mod);
        // Offensive Rebound Actions and Logs
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.suboffRebound();
                mod.addElement("sub player1 " + "Off Reb " +  player1.getoffRebound());
            }else if(flag2 == true){
                player2.suboffRebound();
                mod.addElement("sub player2 " + "Off Reb " +  player2.getoffRebound());
            }else if(flag3 == true){
                player3.suboffRebound();
                mod.addElement("sub player3 " + "Off Reb " +  player3.getoffRebound());
            }else if(flag4 == true){
                player4.suboffRebound();
                mod.addElement("sub player4 " + "Off Reb " +  player4.getoffRebound());
            }else if(flag5 == true){
                player5.suboffRebound();
                mod.addElement("sub player5 " + "Off Reb " +  player5.getoffRebound());
            }else if(flagOpp == true){
                playerOpp.suboffRebound();
                mod.addElement("sub Opponent " + "Off Reb " +  playerOpp.getoffRebound());
            }
        }else{
            if (flag1 == true){
                player1.addoffRebound();
                mod.addElement("player1 " + "Off Reb " +  player1.getoffRebound());
            }else if(flag2 == true){
                player2.addoffRebound();
                mod.addElement("player2 " + "Off Reb " +  player2.getoffRebound());
            }else if(flag3 == true){
                player3.addoffRebound();
                mod.addElement("player3 " + "Off Reb " +  player3.getoffRebound());
            }else if(flag4 == true){
                player4.addoffRebound();
                mod.addElement("player4 " + "Off Reb " +  player4.getoffRebound());
            }else if(flag5 == true){
                player5.addoffRebound();
                mod.addElement("player5 " + "Off Reb " +  player5.getoffRebound());
            }else if(flagOpp == true){
                playerOpp.addoffRebound();
                mod.addElement("Opponent " + "Off Reb " +  playerOpp.getoffRebound());
            }
        }
        refreshScoreboard();
    }//GEN-LAST:event_offReboundButtonActionPerformed

    private void threeMissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeMissButtonActionPerformed
        displayList.setModel(mod);
        // 3pt Miss Actions and Logs
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subthreeMiss();
                mod.addElement("sub player1 " + " 3pt Miss, Points: " +  player1.gettotalPoints());
            }else if(flag2 == true){
                player2.subthreeMiss();
                mod.addElement("sub player2 " + " 3pt Miss, Points: " +  player2.gettotalPoints());
            }else if(flag3 == true){
                player3.subthreeMiss();
                mod.addElement("sub player3 " + " 3pt Miss, Points: " +  player3.gettotalPoints());
            }else if(flag4 == true){
                player4.subthreeMiss();
                mod.addElement("sub player4 " + " 3pt Miss, Points: " +  player4.gettotalPoints());
            }else if(flag5 == true){
                player5.subthreeMiss();
                mod.addElement("sub player5 " + " 3pt Miss, Points: " +  player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.subthreeMiss();
                mod.addElement("sub Opponent " + " 3pt Miss, Points: " +  playerOpp.gettotalPoints());
            }
        }else{
            if (flag1 == true){
                player1.addthreeMiss();
                mod.addElement("player1 " + " 3pt Miss, Points: " +  player1.gettotalPoints());
            }else if(flag2 == true){
                player2.addthreeMiss();
                mod.addElement("player2 " + " 3pt Miss, Points: " +  player2.gettotalPoints());
            }else if(flag3 == true){
                player3.addthreeMiss();
                mod.addElement("player3 " + " 3pt Miss, Points: " +  player3.gettotalPoints());
            }else if(flag4 == true){
                player4.addthreeMiss();
                mod.addElement("player4 " + " 3pt Miss, Points: " +  player4.gettotalPoints());
            }else if(flag5 == true){
                player5.addthreeMiss();
                mod.addElement("player5 " + " 3pt Miss, Points: " +  player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.addthreeMiss();
                mod.addElement("Opponent " + " 3pt Miss, Points: " +  playerOpp.gettotalPoints());
            }
        }
        refreshScoreboard();
    }//GEN-LAST:event_threeMissButtonActionPerformed

    private void twoMissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoMissButtonActionPerformed
        displayList.setModel(mod);
        // TODO add your handling code here:
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subtwoMiss();
                mod.addElement("sub player1 " + "2pt Miss, Points: " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.subtwoMiss();
                mod.addElement("sub player2 " + "2pt Miss, Points: " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.subtwoMiss();
                mod.addElement("sub player3 " + "2pt Miss, Points: " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.subtwoMiss();
                mod.addElement("sub player4 " + "2pt Miss, Points: " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.subtwoMiss();
                mod.addElement("sub player5 " + "2pt Miss, Points: " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.subtwoMiss();
                mod.addElement("sub Opponent " + "2pt Miss, Points: " + playerOpp.gettotalPoints());
            }
        }else{
            if (flag1 == true){
                player1.addtwoMiss();
                mod.addElement("player1 " + "2pt Miss, Points: " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.addtwoMiss();
                mod.addElement("player2 " + "2pt Miss, Points: " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.addtwoMiss();
                mod.addElement("player3 " + "2pt Miss, Points: " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.addtwoMiss();
                mod.addElement("player4 " + "2pt Miss, Points: " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.addtwoMiss();
                mod.addElement("player5 " + "2pt Miss, Points: " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.addtwoMiss();
                mod.addElement("Opponent " + "2pt Miss, Points: " + playerOpp.gettotalPoints());
            }
        }
        refreshScoreboard();
    }//GEN-LAST:event_twoMissButtonActionPerformed

    private void ftMissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftMissButtonActionPerformed
        displayList.setModel(mod);
        // FreeThrow Miss Actions and Logs
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subftMiss();
                mod.addElement("sub player1 " + "FT Miss, Points: " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.subftMiss();
                mod.addElement("sub player2 " + "FT Miss, Points: " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.subftMiss();
                mod.addElement("sub player3 " + "FT Miss, Points: " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.subftMiss();
                mod.addElement("sub player4 " + "FT Miss, Points: " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.subftMiss();
                mod.addElement("sub player5 " + "FT Miss, Points: " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.subftMiss();
                mod.addElement("sub Opponent " + "FT Miss, Points: " + playerOpp.gettotalPoints());
            }
        }else{
            if (flag1 == true){
                player1.addftMiss();
                mod.addElement("player1 " + "FT Miss, Points: " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.addftMiss();
                mod.addElement("player2 " + "FT Miss, Points: " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.addftMiss();
                mod.addElement("player3 " + "FT Miss, Points: " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.addftMiss();
                mod.addElement("player4 " + "FT Miss, Points: " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.addftMiss();
                mod.addElement("player5 " + "FT Miss, Points: " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.addftMiss();
                mod.addElement("Opponent " + "FT Miss, Points: " + playerOpp.gettotalPoints());
            }
        }
        refreshScoreboard();
    }//GEN-LAST:event_ftMissButtonActionPerformed

    private void threeMakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeMakeButtonActionPerformed
        displayList.setModel(mod);
        // 3pt Make Actions and Logs
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subthreeMake();
                mod.addElement("sub player1 " + " 3pt Make, Points: " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.subthreeMake();
                mod.addElement("sub player2 " + " 3pt Make, Points: " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.subthreeMake();
                mod.addElement("sub player3 " + " 3pt Make, Points: " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.subthreeMake();
                mod.addElement("sub player4 " + " 3pt Make, Points: " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.subthreeMake();
                mod.addElement("sub player5 " + " 3pt Make, Points: " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.subthreeMake();
                mod.addElement("sub Opponent " + " 3pt Make, Points: " + playerOpp.gettotalPoints());
            }
        }else{
            if (flag1 == true){
                player1.addthreeMake();
                mod.addElement("player1 " + " 3pt Make, Points: " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.addthreeMake();
                mod.addElement("player2 " + " 3pt Make, Points: " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.addthreeMake();
                mod.addElement("player3 " + " 3pt Make, Points: " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.addthreeMake();
                mod.addElement("player4 " + " 3pt Make, Points: " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.addthreeMake();
                mod.addElement("player5 " + " 3pt Make, Points: " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.addthreeMake();
                mod.addElement("Opponent " + " 3pt Make, Points: " + playerOpp.gettotalPoints());
            }
        }
        refreshScoreboard();
    }//GEN-LAST:event_threeMakeButtonActionPerformed

    private void twoMakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoMakeButtonActionPerformed
        displayList.setModel(mod);
        // 2pt Make Actions and Logs
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subtwoMake();
                mod.addElement("sub player1 " + "2pt Make, Points: " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.subtwoMake();
                mod.addElement("sub player2 " + "2pt Make, Points: " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.subtwoMake();
                mod.addElement("sub player3 " + "2pt Make, Points: " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.subtwoMake();
                mod.addElement("sub player4 " + "2pt Make, Points: " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.subtwoMake();
                mod.addElement("sub player5 " + "2pt Make, Points: " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.subtwoMake();
                mod.addElement("sub Opponent " + "2pt Make, Points: " + playerOpp.gettotalPoints());
            }
        }else{
            if (flag1 == true){
                player1.addtwoMake();
                mod.addElement("player1 " + "2pt Make, Points: " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.addtwoMake();
                mod.addElement("player2 " + "2pt Make, Points: " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.addtwoMake();
                mod.addElement("player3 " + "2pt Make, Points: " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.addtwoMake();
                mod.addElement("player4 " + "2pt Make, Points: " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.addtwoMake();
                mod.addElement("player5 " + "2pt Make, Points: " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.addtwoMake();
                mod.addElement("Opponent " + "2pt Make, Points: " + playerOpp.gettotalPoints());
            }
        }
        refreshScoreboard();
    }//GEN-LAST:event_twoMakeButtonActionPerformed

    private void ftMakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftMakeButtonActionPerformed
        displayList.setModel(mod);
        // FreeThrow Make Actions and Logs
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subftMake();
                mod.addElement("sub player1 " + "FT Make, Points: " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.subftMake();
                mod.addElement("sub player2 " + "FT Make, Points: " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.subftMake();
                mod.addElement("sub player3 " + "FT Make, Points: " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.subftMake();
                mod.addElement("sub player4 " + "FT Make, Points: " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.subftMake();
                mod.addElement("sub player5 " + "FT Make, Points: " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.subftMake();
                mod.addElement("sub Opponent " + "FT Make, Points: " + playerOpp.gettotalPoints());
            }
        }else{
            if (flag1 == true){
                player1.addftMake();
                mod.addElement("player1 " + "FT Make, Points: " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.addftMake();
                mod.addElement("player2 " + "FT Make, Points: " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.addftMake();
                mod.addElement("player3 " + "FT Make, Points: " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.addftMake();
                mod.addElement("player4 " + "FT Make, Points: " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.addftMake();
                mod.addElement("player5 " + "FT Make, Points: " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.addftMake();
                mod.addElement("Opponent " + "FT Make, Points: " + playerOpp.gettotalPoints());
            }
        }
        refreshScoreboard();
    }//GEN-LAST:event_ftMakeButtonActionPerformed

    private void RBSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBSubtractActionPerformed
        // PlaceHolder
    }//GEN-LAST:event_RBSubtractActionPerformed

   //Register Button Press for playerOpp
    private void oppButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oppButActionPerformed
        // TODO add your handling code here:
        resetFlags();
        flagOpp = true;
    }//GEN-LAST:event_oppButActionPerformed

    private void player5ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player5ButActionPerformed
        // TODO add your handling code here:
        resetFlags();
        flag5 = true;
    }//GEN-LAST:event_player5ButActionPerformed

    private void player4ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player4ButActionPerformed
        // TODO add your handling code here:
        resetFlags();
        flag4 = true;
    }//GEN-LAST:event_player4ButActionPerformed

    private void player3ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player3ButActionPerformed
        // TODO add your handling code here:
        resetFlags();
        flag3 = true;
    }//GEN-LAST:event_player3ButActionPerformed

    private void player2ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2ButActionPerformed
        // TODO add your handling code here:
        resetFlags();
        flag2 = true;
    }//GEN-LAST:event_player2ButActionPerformed

    private void player1ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1ButActionPerformed
        // TODO add your handling code here:
        resetFlags();
        flag1 = true;
    }//GEN-LAST:event_player1ButActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void resetFlags(){
        flag1 = false;
        flag2 = false;
        flag3 = false;
        flag4 = false;
        flag5 = false;
        flagOpp = false;
    }
    
    //Team Stats methods
    public int calculateteamScore(){
        teamScore = (player1.gettotalPoints() + player2.gettotalPoints() + player3.gettotalPoints() + player4.gettotalPoints() + player5.gettotalPoints());
        return teamScore;
    }
    public int calculateteamftMake(){
        teamftMake = (player1.getftMake() + player2.getftMake() + player3.getftMake() + player4.getftMake() + player5.getftMake());
        return teamftMake;
    }
    public int calculateteamftMiss(){
        teamftMiss = (player1.getftMiss() + player2.getftMiss() + player3.getftMiss() + player4.getftMiss() + player5.getftMiss());
        return teamftMiss;
    }
    public int calculateteamftAtt(){
        teamftAtt = calculateteamftMake() + calculateteamftMiss();
        return teamftAtt;
    }
    public double calculateteamftPerc(){
        double num1 = calculateteamftMake();
        double num2 = calculateteamftAtt();
        if (num2 <= 0){
            return 0;
        }else{
            teamftPerc = (num1 / num2) * 100;     
        return teamftPerc;
        }
    }
    public int calculateteamtwoMake(){
        teamtwoMake = (player1.gettwoMake() + player2.gettwoMake() + player3.gettwoMake() + player4.gettwoMake() + player5.gettwoMake());
        return teamtwoMake;
    }
    public int calculateteamtwoMiss(){
        teamtwoMiss = (player1.gettwoMiss() + player2.gettwoMiss() + player3.gettwoMiss() + player4.gettwoMiss() + player5.gettwoMiss());
        return teamtwoMiss;
    }
    public int calculateteamtwoAtt(){
        teamtwoAtt = calculateteamtwoMake() + calculateteamtwoMiss();
        return teamtwoAtt;
    }
    public double calculateteamtwoPerc(){
        double num1 = calculateteamtwoMake();
        double num2 = calculateteamtwoAtt();
        if (num2 <= 0){
            return 0;
        }else{
            teamtwoPerc = (num1 / num2) * 100;     
        return teamtwoPerc;
        }
    }
    public int calculateteamthreeMake(){
        teamthreeMake = (player1.getthreeMake() + player2.getthreeMake() + player3.getthreeMake() + player4.getthreeMake() + player5.getthreeMake());
        return teamthreeMake;
    }
    public int calculateteamthreeMiss(){
        teamthreeMiss = (player1.getthreeMiss() + player2.getthreeMiss() + player3.getthreeMiss() + player4.getthreeMiss() + player5.getthreeMiss());
        return teamthreeMiss;
    }
    public int calculateteamthreeAtt(){
        teamthreeAtt = calculateteamthreeMake() + calculateteamthreeMiss();
        return teamthreeAtt;
    }
    public double calculateteamthreePerc(){
        double num1 = calculateteamthreeMake();
        double num2 = calculateteamthreeMake() + calculateteamthreeMiss();
        if (num2 <= 0){
            return 0;
        }else{
            teamthreePerc = (num1 / num2) * 100;     
        return teamthreePerc;
        }
    }
    public int calculateteamoffRebound(){
        teamoffRebound = (player1.getoffRebound() + player2.getoffRebound() + player3.getoffRebound() + player4.getoffRebound() + player5.getoffRebound());
        return teamoffRebound;
    }
    public int calculateteamdefRebound(){
        teamdefRebound = (player1.getdefRebound() + player2.getdefRebound() + player3.getdefRebound() + player4.getdefRebound() + player5.getdefRebound());
        return teamdefRebound;
    }
    public int calculateteamtotalRebound(){
        teamtotalRebound = calculateteamoffRebound() + calculateteamdefRebound();
        return teamtotalRebound;
    }
    public int calculateteamAssist(){
        teamAssist = (player1.getAssist() + player2.getAssist() + player3.getAssist() + player4.getAssist() + player5.getAssist());
        return teamAssist;
    }
    public int calculateteamTurnover(){
        teamTurnover = (player1.getTurnover() + player2.getTurnover() + player3.getTurnover() + player4.getTurnover() + player5.getTurnover());
        return teamTurnover;
    }
    public int calculateteamSteal(){
        teamSteal = (player1.getSteal() + player2.getSteal() + player3.getSteal() + player4.getSteal() + player5.getSteal());
        return teamSteal;
    }
    public int calculateteamBlock(){
        teamBlock = (player1.getBlock() + player2.getBlock() + player3.getBlock() + player4.getBlock() + player5.getBlock());
        return teamBlock;
    }
    public int calculateteamFoul(){
        teamFoul = (player1.getFoul() + player2.getFoul() + player3.getFoul() + player4.getFoul() + player5.getFoul());
        return teamFoul;
    }
    
    public void refreshTable(){
        //Create Columns
        String[] columns1 = {"Name/Number", "2pt Att.", "2pt Made", "2pt %", "3pt Att.", "3pt Made", "3pt %", "FT Att.", "FT Made", "FT %",
            "Off Reb", "Def Reb", "Total Reb", "Steals", "Turnovers", "Assists", "Blocks", "Fouls"};
        String [][] data1 = {{String.valueOf(player1.getName()), String.valueOf(player1.gettwoAtt()), String.valueOf(player1.gettwoMake()),
        String.valueOf(player1.gettwoPerc()) + "%", String.valueOf(player1.getthreeAtt()), String.valueOf(player1.getthreeMake()), String.valueOf(player1.getthreePerc()) + "%",
        String.valueOf(player1.getftAtt()), String.valueOf(player1.getftMake()), String.valueOf(player1.getftPerc()) + "%", String.valueOf(player1.getoffRebound()),
        String.valueOf(player1.getdefRebound()), String.valueOf(player1.gettotalRebound()), String.valueOf(player1.getSteal()),
        String.valueOf(player1.getTurnover()), String.valueOf(player1.getAssist()), String.valueOf(player1.getBlock()), String.valueOf(player1.getFoul())},
        {String.valueOf(player2.getName()), String.valueOf(player2.gettwoAtt()), String.valueOf(player2.gettwoMake()),
        String.valueOf(player2.gettwoPerc()) + "%", String.valueOf(player2.getthreeAtt()), String.valueOf(player2.getthreeMake()), String.valueOf(player2.getthreePerc()) + "%",
        String.valueOf(player2.getftAtt()), String.valueOf(player2.getftMake()), String.valueOf(player2.getftPerc()) + "%", String.valueOf(player2.getoffRebound()),
        String.valueOf(player2.getdefRebound()), String.valueOf(player2.gettotalRebound()), String.valueOf(player2.getSteal()),
        String.valueOf(player2.getTurnover()), String.valueOf(player2.getAssist()), String.valueOf(player2.getBlock()), String.valueOf(player2.getFoul())},
        {String.valueOf(player3.getName()), String.valueOf(player3.gettwoAtt()), String.valueOf(player3.gettwoMake()),
        String.valueOf(player3.gettwoPerc()) + "%", String.valueOf(player3.getthreeAtt()), String.valueOf(player3.getthreeMake()), String.valueOf(player3.getthreePerc()) + "%",
        String.valueOf(player3.getftAtt()), String.valueOf(player3.getftMake()), String.valueOf(player3.getftPerc()) + "%", String.valueOf(player3.getoffRebound()),
        String.valueOf(player3.getdefRebound()), String.valueOf(player3.gettotalRebound()), String.valueOf(player3.getSteal()),
        String.valueOf(player3.getTurnover()), String.valueOf(player3.getAssist()), String.valueOf(player3.getBlock()), String.valueOf(player3.getFoul())},
        {String.valueOf(player4.getName()), String.valueOf(player4.gettwoAtt()), String.valueOf(player4.gettwoMake()),
        String.valueOf(player4.gettwoPerc()) + "%", String.valueOf(player4.getthreeAtt()), String.valueOf(player4.getthreeMake()), String.valueOf(player4.getthreePerc()) + "%",
        String.valueOf(player4.getftAtt()), String.valueOf(player4.getftMake()), String.valueOf(player4.getftPerc()) + "%", String.valueOf(player4.getoffRebound()),
        String.valueOf(player4.getdefRebound()), String.valueOf(player4.gettotalRebound()), String.valueOf(player4.getSteal()),
        String.valueOf(player4.getTurnover()), String.valueOf(player4.getAssist()), String.valueOf(player4.getBlock()), String.valueOf(player4.getFoul())},
        {String.valueOf(player5.getName()), String.valueOf(player5.gettwoAtt()), String.valueOf(player5.gettwoMake()),
        String.valueOf(player5.gettwoPerc()) + "%", String.valueOf(player5.getthreeAtt()), String.valueOf(player5.getthreeMake()), String.valueOf(player5.getthreePerc()) + "%",
        String.valueOf(player5.getftAtt()), String.valueOf(player5.getftMake()), String.valueOf(player5.getftPerc()) + "%", String.valueOf(player5.getoffRebound()),
        String.valueOf(player5.getdefRebound()), String.valueOf(player5.gettotalRebound()), String.valueOf(player5.getSteal()),
        String.valueOf(player5.getTurnover()), String.valueOf(player5.getAssist()), String.valueOf(player5.getBlock()), String.valueOf(player5.getFoul())}};
        
        DefaultTableModel table1 = (DefaultTableModel) statTable.getModel();
        table1.setDataVector(data1,columns1);
        statTable.setRowHeight(30);
        //Set Column Widths Table 1
        statTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        statTable.getColumnModel().getColumn(1).setPreferredWidth(55);
        statTable.getColumnModel().getColumn(2).setPreferredWidth(65);
        statTable.getColumnModel().getColumn(3).setPreferredWidth(55);
        statTable.getColumnModel().getColumn(4).setPreferredWidth(55);
        statTable.getColumnModel().getColumn(5).setPreferredWidth(65);
        statTable.getColumnModel().getColumn(6).setPreferredWidth(55);
        statTable.getColumnModel().getColumn(7).setPreferredWidth(65);
        statTable.getColumnModel().getColumn(8).setPreferredWidth(55);
        statTable.getColumnModel().getColumn(9).setPreferredWidth(65);
        statTable.getColumnModel().getColumn(10).setPreferredWidth(55);
        statTable.setBorder(BorderFactory.createEmptyBorder(12,12,12,12));
        statTable.setShowGrid(true);
        statTable.setGridColor(Color.LIGHT_GRAY);
        
        
        String [][] data2 = {{"Team", String.valueOf(calculateteamtwoMake()), String.valueOf(calculateteamtwoMiss()),
        String.valueOf(calculateteamtwoPerc()) + "%", String.valueOf(calculateteamthreeAtt()), String.valueOf(calculateteamthreeMake()), String.valueOf(calculateteamthreePerc()) + "%",
        String.valueOf(calculateteamftAtt()), String.valueOf(calculateteamftMake()), String.valueOf(calculateteamftPerc()) + "%", String.valueOf(calculateteamoffRebound()),
        String.valueOf(calculateteamdefRebound()), String.valueOf(calculateteamtotalRebound()), String.valueOf(calculateteamSteal()),
        String.valueOf(calculateteamTurnover()), String.valueOf(calculateteamAssist()), String.valueOf(calculateteamBlock()), String.valueOf(calculateteamFoul())},
        {"Opponent", String.valueOf(playerOpp.gettwoAtt()), String.valueOf(playerOpp.gettwoMake()),
        String.valueOf(playerOpp.gettwoPerc()) + "%", String.valueOf(playerOpp.getthreeAtt()), String.valueOf(playerOpp.getthreeMake()), String.valueOf(playerOpp.getthreePerc()) + "%",
        String.valueOf(playerOpp.getftAtt()), String.valueOf(playerOpp.getftMake()), String.valueOf(playerOpp.getftPerc()) + "%", String.valueOf(playerOpp.getoffRebound()),
        String.valueOf(playerOpp.getdefRebound()), String.valueOf(playerOpp.gettotalRebound()), String.valueOf(playerOpp.getSteal()),
        String.valueOf(playerOpp.getTurnover()), String.valueOf(playerOpp.getAssist()), String.valueOf(playerOpp.getBlock()), String.valueOf(playerOpp.getFoul())}
        };
        
        DefaultTableModel table2 = (DefaultTableModel) statTable2.getModel();
        table2.setDataVector(data2,columns1);
        statTable2.setRowHeight(30);
        //Set Column Widths
        statTable2.getColumnModel().getColumn(0).setPreferredWidth(100);
        statTable2.getColumnModel().getColumn(1).setPreferredWidth(55);
        statTable2.getColumnModel().getColumn(2).setPreferredWidth(65);
        statTable2.getColumnModel().getColumn(3).setPreferredWidth(55);
        statTable2.getColumnModel().getColumn(4).setPreferredWidth(55);
        statTable2.getColumnModel().getColumn(5).setPreferredWidth(65);
        statTable2.getColumnModel().getColumn(6).setPreferredWidth(55);
        statTable2.getColumnModel().getColumn(7).setPreferredWidth(65);
        statTable2.getColumnModel().getColumn(8).setPreferredWidth(55);
        statTable2.getColumnModel().getColumn(9).setPreferredWidth(65);
        statTable2.getColumnModel().getColumn(10).setPreferredWidth(55);
        statTable2.setBorder(BorderFactory.createEmptyBorder(12,12,12,12));
        statTable2.setShowGrid(true);
        statTable2.setGridColor(Color.LIGHT_GRAY);
    }
    public void refreshScoreboard(){
        teamScoreBoard.setText(String.valueOf(calculateteamScore()));
        oppScoreBoard.setText(String.valueOf(playerOpp.gettotalPoints()));
        teamFoulBoard.setText(String.valueOf(calculateteamFoul()));
        oppFoulBoard.setText(String.valueOf(playerOpp.getFoul()));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BballUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BballUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BballUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BballUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BballUI().setVisible(true);
            }
        });
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBSubtract;
    private javax.swing.JButton assistButton;
    private javax.swing.JButton blockButton;
    private javax.swing.JButton defReboundButton;
    private javax.swing.JList displayList;
    private javax.swing.JButton foulButton;
    private javax.swing.JButton ftMakeButton;
    private javax.swing.JButton ftMissButton;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu menuEditNames;
    private javax.swing.JMenuItem menuNameEdit1;
    private javax.swing.JMenuItem menuNameEdit2;
    private javax.swing.JMenuItem menuNameEdit3;
    private javax.swing.JMenuItem menuNameEdit4;
    private javax.swing.JMenuItem menuNameEdit5;
    private javax.swing.JButton offReboundButton;
    private javax.swing.JButton oppBut;
    private javax.swing.JLabel oppFoulBoard;
    private javax.swing.JLabel oppScoreBoard;
    private javax.swing.JButton player1But;
    private javax.swing.JButton player2But;
    private javax.swing.JButton player3But;
    private javax.swing.JButton player4But;
    private javax.swing.JButton player5But;
    private javax.swing.JTable statTable;
    private javax.swing.JTable statTable2;
    private javax.swing.JButton stealButton;
    private javax.swing.JButton tableRefreshButton;
    private javax.swing.JLabel teamFoulBoard;
    private javax.swing.JLabel teamScoreBoard;
    private javax.swing.JButton threeMakeButton;
    private javax.swing.JButton threeMissButton;
    private javax.swing.JButton turnoverButton;
    private javax.swing.JButton twoMakeButton;
    private javax.swing.JButton twoMissButton;
    // End of variables declaration//GEN-END:variables

}
