
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author stephensmac
 */
public class BballUI extends javax.swing.JFrame {

    Player player1 = new Player();
    Player player2 = new Player();
    Player player3 = new Player();
    Player player4 = new Player();
    Player player5 = new Player();
    Player playerOpp = new Player();
    
    //Flags for button combos
    boolean flag1 = false;
    boolean flag2 = false;
    boolean flag3 = false;
    boolean flag4 = false;
    boolean flag5 = false;
    boolean flagOpp = false;

    //Team Stats
    int teamScore;
    int teamftMake;
    int teamftMiss;
    int teamtwoMake;
    int teamtwoMiss;
    int teamthreeMake;
    int teamthreeMiss;
    int teamoffRebound;
    int teamdefRebound;
    /**
     * Creates new form BballUI
     */
    public BballUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        player1But = new javax.swing.JButton();
        player2But = new javax.swing.JButton();
        player3But = new javax.swing.JButton();
        player4But = new javax.swing.JButton();
        player5But = new javax.swing.JButton();
        oppBut = new javax.swing.JButton();
        RBSubtract = new javax.swing.JRadioButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ftMakeButton = new javax.swing.JButton();
        twoMakeButton = new javax.swing.JButton();
        threeMakeButton = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ftMissButton = new javax.swing.JButton();
        twoMissButton = new javax.swing.JButton();
        threeMissButton = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel17 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuEditNames = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));

        player1But.setText("Player 1");
        player1But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1ButActionPerformed(evt);
            }
        });

        player2But.setText("Player 2");
        player2But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2ButActionPerformed(evt);
            }
        });

        player3But.setText("Player 3");
        player3But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player3ButActionPerformed(evt);
            }
        });

        player4But.setText("Player 4");
        player4But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player4ButActionPerformed(evt);
            }
        });

        player5But.setText("Player 5");
        player5But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player5ButActionPerformed(evt);
            }
        });

        oppBut.setText("Opponent");
        oppBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oppButActionPerformed(evt);
            }
        });

        RBSubtract.setText("Subtract");
        RBSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBSubtractActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(player4But)
                        .addGap(31, 31, 31)
                        .addComponent(player5But))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(player1But)
                        .addGap(32, 32, 32)
                        .addComponent(player2But)
                        .addGap(31, 31, 31)
                        .addComponent(player3But)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBSubtract)
                    .addComponent(oppBut))
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(player1But, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player3But, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player2But, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(player4But, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(player5But, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(oppBut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RBSubtract)
                        .addGap(26, 26, 26))))
        );

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new java.awt.Color(153, 255, 255));

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setText("Make");

        ftMakeButton.setText("FT");
        ftMakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftMakeButtonActionPerformed(evt);
            }
        });

        twoMakeButton.setText("2");
        twoMakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoMakeButtonActionPerformed(evt);
            }
        });

        threeMakeButton.setText("3");
        threeMakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeMakeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ftMakeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(twoMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threeMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(ftMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(twoMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(threeMakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(255, 51, 51));

        jLabel2.setText("Miss");

        ftMissButton.setText("FT");
        ftMissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftMissButtonActionPerformed(evt);
            }
        });

        twoMissButton.setText("2");
        twoMissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoMissButtonActionPerformed(evt);
            }
        });

        threeMissButton.setText("3");
        threeMissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeMissButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(twoMissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(threeMissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ftMissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(ftMissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(twoMissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(threeMissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel3.setText("Offense");

        jButton43.setText("Rebound");

        jButton44.setText("Assist");

        jButton45.setText("Turnover");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel3))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel4.setText("Defense");

        jButton46.setText("Rebound");

        jButton47.setText("Steal");

        jButton48.setText("Block");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel4))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton48, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton46, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(jButton47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("User Interface", jPanel9);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 876, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Stat Sheet", jPanel17);

        jMenu1.setText("Bball");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menuEditNames.setText("Edit Player Names");
        jMenu2.add(menuEditNames);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Register Button Press for player 1
    private void player1ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1ButActionPerformed
        // TODO add your handling code here:
        resetFlags();
        flag1 = true;
    }//GEN-LAST:event_player1ButActionPerformed
    //Register Button Press for player 2
    private void player2ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2ButActionPerformed
        // TODO add your handling code here:
        resetFlags();
        flag2 = true;
    }//GEN-LAST:event_player2ButActionPerformed
    //Register Button Press for player 3
    private void player3ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player3ButActionPerformed
        // TODO add your handling code here:
        resetFlags();
        flag3 = true;
    }//GEN-LAST:event_player3ButActionPerformed
    //Register Button Press for player 4
    private void player4ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player4ButActionPerformed
        // TODO add your handling code here:
        resetFlags();
        flag4 = true;
    }//GEN-LAST:event_player4ButActionPerformed
    //Register Button Press for player 5
    private void player5ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player5ButActionPerformed
        // TODO add your handling code here:
        resetFlags();
        flag5 = true;
    }//GEN-LAST:event_player5ButActionPerformed
    //Register Button Press for playerOpp
    private void oppButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oppButActionPerformed
        // TODO add your handling code here:
        resetFlags();
        flagOpp = true;
    }//GEN-LAST:event_oppButActionPerformed

    private void RBSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBSubtractActionPerformed
        // PlaceHolder
    }//GEN-LAST:event_RBSubtractActionPerformed

    private void ftMakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftMakeButtonActionPerformed
        // TODO add your handling code here:
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subftMake();
                System.out.println("sub player1 " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.subftMake();
                System.out.println("sub player2 " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.subftMake();
                System.out.println("sub player3 " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.subftMake();
                System.out.println("sub player4 " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.subftMake();
                System.out.println("sub player5 " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.subftMake();
                System.out.println("sub Opponent " + playerOpp.gettotalPoints());
            }
        }else{
            if (flag1 == true){
                player1.addftMake();
                System.out.println("player1 " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.addftMake();
                System.out.println("player2 " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.addftMake();
                System.out.println("player3 " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.addftMake();
                System.out.println("player4 " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.addftMake();
                System.out.println("player5 " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.addftMake();
                System.out.println("Opponent " + playerOpp.gettotalPoints());
            }
        }
    }//GEN-LAST:event_ftMakeButtonActionPerformed

    private void ftMissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftMissButtonActionPerformed
        // TODO add your handling code here:
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subftMiss();
                System.out.println("sub player1 " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.subftMiss();
                System.out.println("sub player2 " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.subftMiss();
                System.out.println("sub player3 " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.subftMiss();
                System.out.println("sub player4 " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.subftMiss();
                System.out.println("sub player5 " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.subftMiss();
                System.out.println("sub Opponent " + playerOpp.gettotalPoints());
            }
        }else{
            if (flag1 == true){
                player1.addftMiss();
                System.out.println("player1 " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.addftMiss();
                System.out.println("player2 " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.addftMiss();
                System.out.println("player3 " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.addftMiss();
                System.out.println("player4 " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.addftMiss();
                System.out.println("player5 " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.addftMiss();
                System.out.println("Opponent " + playerOpp.gettotalPoints());
            }
        }
    }//GEN-LAST:event_ftMissButtonActionPerformed

    private void twoMakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoMakeButtonActionPerformed
        // TODO add your handling code here:
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subtwoMake();
                System.out.println("sub player1 " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.subtwoMake();
                System.out.println("sub player2 " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.subtwoMake();
                System.out.println("sub player3 " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.subtwoMake();
                System.out.println("sub player4 " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.subtwoMake();
                System.out.println("sub player5 " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.subtwoMake();
                System.out.println("sub Opponent " + playerOpp.gettotalPoints());
            }
        }else{
            if (flag1 == true){
                player1.addtwoMake();
                System.out.println("player1 " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.addtwoMake();
                System.out.println("player2 " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.addtwoMake();
                System.out.println("player3 " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.addtwoMake();
                System.out.println("player4 " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.addtwoMake();
                System.out.println("player5 " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.addtwoMake();
                System.out.println("Opponent " + playerOpp.gettotalPoints());
            }
        }
    }//GEN-LAST:event_twoMakeButtonActionPerformed

    private void twoMissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoMissButtonActionPerformed
        // TODO add your handling code here:
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subtwoMake();
                System.out.println("sub player1 " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.subtwoMake();
                System.out.println("sub player2 " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.subtwoMake();
                System.out.println("sub player3 " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.subtwoMake();
                System.out.println("sub player4 " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.subtwoMake();
                System.out.println("sub player5 " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.subtwoMake();
                System.out.println("sub Opponent " + playerOpp.gettotalPoints());
            }
        }else{
            if (flag1 == true){
                player1.addtwoMake();
                System.out.println("player1 " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.addtwoMake();
                System.out.println("player2 " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.addtwoMake();
                System.out.println("player3 " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.addtwoMake();
                System.out.println("player4 " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.addtwoMake();
                System.out.println("player5 " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.addtwoMake();
                System.out.println("Opponent " + playerOpp.gettotalPoints());
            }
        }
    }//GEN-LAST:event_twoMissButtonActionPerformed

    private void threeMakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeMakeButtonActionPerformed
        // TODO add your handling code here:
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subthreeMake();
                System.out.println("sub player1 " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.subthreeMake();
                System.out.println("sub player2 " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.subthreeMake();
                System.out.println("sub player3 " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.subthreeMake();
                System.out.println("sub player4 " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.subthreeMake();
                System.out.println("sub player5 " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.subthreeMake();
                System.out.println("sub Opponent " + playerOpp.gettotalPoints());
            }
        }else{
            if (flag1 == true){
                player1.addthreeMake();
                System.out.println("player1 " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.addthreeMake();
                System.out.println("player2 " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.addthreeMake();
                System.out.println("player3 " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.addthreeMake();
                System.out.println("player4 " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.addthreeMake();
                System.out.println("player5 " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.addthreeMake();
                System.out.println("Opponent " + playerOpp.gettotalPoints());
            }
        }
    }//GEN-LAST:event_threeMakeButtonActionPerformed

    private void threeMissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeMissButtonActionPerformed
        // TODO add your handling code here:
        if (RBSubtract.isSelected()){
            if (flag1 == true){
                player1.subtwoMake();
                System.out.println("sub player1 " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.subtwoMake();
                System.out.println("sub player2 " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.subtwoMake();
                System.out.println("sub player3 " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.subtwoMake();
                System.out.println("sub player4 " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.subtwoMake();
                System.out.println("sub player5 " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.subtwoMake();
                System.out.println("sub Opponent " + playerOpp.gettotalPoints());
            }
        }else{
            if (flag1 == true){
                player1.addtwoMake();
                System.out.println("player1 " + player1.gettotalPoints());
            }else if(flag2 == true){
                player2.addtwoMake();
                System.out.println("player2 " + player2.gettotalPoints());
            }else if(flag3 == true){
                player3.addtwoMake();
                System.out.println("player3 " + player3.gettotalPoints());
            }else if(flag4 == true){
                player4.addtwoMake();
                System.out.println("player4 " + player4.gettotalPoints());
            }else if(flag5 == true){
                player5.addtwoMake();
                System.out.println("player5 " + player5.gettotalPoints());
            }else if(flagOpp == true){
                playerOpp.addtwoMake();
                System.out.println("Opponent " + playerOpp.gettotalPoints());
            }
        }
    }//GEN-LAST:event_threeMissButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    public void resetFlags(){
        flag1 = false;
        flag2 = false;
        flag3 = false;
        flag4 = false;
        flag5 = false;
        flagOpp = false;
    }
    
    //Team Stats methods
    public int calculateteamScore(){
        teamScore = (player1.gettotalPoints() + player2.gettotalPoints() + player3.gettotalPoints() + player4.gettotalPoints() + player5.gettotalPoints());
        return teamScore;
    }
    public int calculateteamftMake(){
        teamftMake = (player1.getftMake() + player2.getftMake() + player3.getftMake() + player4.getftMake() + player5.getftMake());
        return teamftMake;
    }
    public int calculateteamftMiss(){
        teamftMiss = (player1.getftMiss() + player2.getftMiss() + player3.getftMiss() + player4.getftMiss() + player5.getftMiss());
        return teamftMiss;
    }
    public int calculateteamtwoMake(){
        teamtwoMake = (player1.gettwoMake() + player2.gettwoMake() + player3.gettwoMake() + player4.gettwoMake() + player5.gettwoMake());
        return teamtwoMake;
    }
    public int calculateteamtwoMiss(){
        teamtwoMiss = (player1.gettwoMiss() + player2.gettwoMiss() + player3.gettwoMiss() + player4.gettwoMiss() + player5.gettwoMiss());
        return teamtwoMiss;
    }
    public int calculateteamthreeMake(){
        teamthreeMake = (player1.getthreeMake() + player2.getthreeMake() + player3.getthreeMake() + player4.getthreeMake() + player5.getthreeMake());
        return teamthreeMake;
    }
    public int calculateteamthreeMiss(){
        teamthreeMiss = (player1.getthreeMiss() + player2.getthreeMiss() + player3.getthreeMiss() + player4.getthreeMiss() + player5.getthreeMiss());
        return teamthreeMiss;
    }
    public int calculateteamoffRebound(){
        teamoffRebound = (player1.getoffRebound() + player2.getoffRebound() + player3.getoffRebound() + player4.getoffRebound() + player5.getoffRebound());
        return teamoffRebound;
    }
    public int calculateteamdefRebound(){
        teamdefRebound = (player1.getdefRebound() + player2.getdefRebound() + player3.getdefRebound() + player4.getdefRebound() + player5.getdefRebound());
        return teamdefRebound;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BballUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BballUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BballUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BballUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BballUI().setVisible(true);
            }
        });
        
        
        
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBSubtract;
    private javax.swing.JButton ftMakeButton;
    private javax.swing.JButton ftMissButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu menuEditNames;
    private javax.swing.JButton oppBut;
    private javax.swing.JButton player1But;
    private javax.swing.JButton player2But;
    private javax.swing.JButton player3But;
    private javax.swing.JButton player4But;
    private javax.swing.JButton player5But;
    private javax.swing.JButton threeMakeButton;
    private javax.swing.JButton threeMissButton;
    private javax.swing.JButton twoMakeButton;
    private javax.swing.JButton twoMissButton;
    // End of variables declaration//GEN-END:variables

}
